# Generated by Django 2.0 on 2018-08-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id:')),
                ('alternativaDescripcion', models.CharField(max_length=500, verbose_name='Descripcion de la Pregunta:')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id:')),
                ('preguntaDescripcion', models.CharField(max_length=500, verbose_name='Descripcion de la Pregunta:')),
                ('tipoPregunta', models.CharField(max_length=10, verbose_name='Tipo de Pregunta:')),
                ('tieneAlternativas', models.CharField(max_length=10, verbose_name='Tiene Alternativas:')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creacion:')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha Actualizacion:')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado:')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='alternativas',
            name='idPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.Preguntas'),
        ),
    ]
