# Generated by Django 2.0 on 2018-08-08 21:23

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=500)),
                ('tipo_mensaje', models.CharField(max_length=10)),
                ('estado_mensaje', models.CharField(max_length=10)),
                ('id_e', models.CharField(default='', max_length=10)),
                ('id_r', models.CharField(default='', max_length=10)),
                ('timestamp', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChatsGrupos',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=500)),
                ('tipo_mensaje', models.CharField(max_length=10)),
                ('estado_mensaje', models.CharField(max_length=10)),
                ('id_e', models.CharField(default='', max_length=10)),
                ('timestamp', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Chat Grupo',
                'verbose_name_plural': 'Chats Grupos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GrupoChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creacion:')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('foto', models.FileField(upload_to=Main.models.get_upload_file_name)),
            ],
            options={
                'verbose_name': 'Grupo Chat',
                'verbose_name_plural': 'Grupos Chats',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantesGrupo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_r', models.CharField(default='', max_length=10)),
                ('tipo_mensaje', models.CharField(max_length=10)),
                ('mensaje', models.CharField(max_length=500)),
                ('estado_mensaje', models.CharField(max_length=10)),
                ('id_chat_grupo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Main.ChatsGrupos')),
                ('id_g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.GrupoChat')),
            ],
            options={
                'verbose_name': 'Participante Grupo',
                'verbose_name_plural': 'Participantes Grupos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsuariosExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creacion:')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha Actualizacion:')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('estado_notificacion', models.BooleanField(default=False, verbose_name='Estado:')),
                ('foto', models.FileField(upload_to=Main.models.get_upload_file_name)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Extra',
                'verbose_name_plural': 'Usuarios Extras',
                'ordering': ['usuario'],
            },
        ),
        migrations.AddField(
            model_name='chatsgrupos',
            name='id_g',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.GrupoChat'),
        ),
    ]
